// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace api.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230605163257_RWorkVendaPecaV6_5")]
    partial class RWorkVendaPecaV6_5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Api.Entities.Chamados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCliente")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.ToTable("chamados");
                });

            modelBuilder.Entity("Api.Entities.ClientApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CNPJ")
                        .HasColumnType("TEXT");

                    b.Property<float>("Dividas")
                        .HasColumnType("REAL");

                    b.Property<string>("Endereco")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameClient")
                        .HasColumnType("TEXT");

                    b.Property<int>("QNTBicos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QNTTanques")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("clientApps");
                });

            modelBuilder.Entity("Api.Entities.Contatos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdClient")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Numero")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.ToTable("contatos");
                });

            modelBuilder.Entity("Api.Entities.ItemPeca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPeca")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdVendaPeca")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PecaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreUni")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Qnt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdVendaPeca");

                    b.HasIndex("PecaId");

                    b.ToTable("itemPeca");
                });

            modelBuilder.Entity("Api.Entities.Peca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamePeca")
                        .HasColumnType("TEXT");

                    b.Property<float>("ValorUnit")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("peca");
                });

            modelBuilder.Entity("Api.Entities.Servicos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescPagamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCliente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPeca")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NomeTecnico")
                        .HasColumnType("nvarchar(20)");

                    b.Property<float>("ValorServico")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdPeca");

                    b.ToTable("servicos");
                });

            modelBuilder.Entity("Api.Entities.UserApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChaveSenha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Nivel_User")
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Senha")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("userApps");
                });

            modelBuilder.Entity("Api.Entities.VendaPeca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCliente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdItemPeca")
                        .HasColumnType("INTEGER");

                    b.Property<float>("ValorTotal")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.ToTable("vendaPecas");
                });

            modelBuilder.Entity("Api.Entities.Chamados", b =>
                {
                    b.HasOne("Api.Entities.ClientApp", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Api.Entities.Contatos", b =>
                {
                    b.HasOne("Api.Entities.ClientApp", "ClientApp")
                        .WithMany("Contatos")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientApp");
                });

            modelBuilder.Entity("Api.Entities.ItemPeca", b =>
                {
                    b.HasOne("Api.Entities.VendaPeca", "VendaPeca")
                        .WithMany("ItemPeca")
                        .HasForeignKey("IdVendaPeca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Entities.Peca", "Peca")
                        .WithMany()
                        .HasForeignKey("PecaId");

                    b.Navigation("Peca");

                    b.Navigation("VendaPeca");
                });

            modelBuilder.Entity("Api.Entities.Servicos", b =>
                {
                    b.HasOne("Api.Entities.ClientApp", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Entities.Peca", "Peca")
                        .WithMany()
                        .HasForeignKey("IdPeca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Peca");
                });

            modelBuilder.Entity("Api.Entities.VendaPeca", b =>
                {
                    b.HasOne("Api.Entities.ClientApp", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Api.Entities.ClientApp", b =>
                {
                    b.Navigation("Contatos");
                });

            modelBuilder.Entity("Api.Entities.VendaPeca", b =>
                {
                    b.Navigation("ItemPeca");
                });
#pragma warning restore 612, 618
        }
    }
}
